### ISSUE TITLE
Keyboard shortcuts not working properly.

### ISSUE THREAD

**Issue by eek** [whitecrownclown/videoplayer#2]
Don't know if it's an Ubuntu only issue, but hitting "space" works only the first time, the second time, it no longer takes keyboard shortcuts (neither play/resume nor mute/unmute or fullscreen).

Seems that by changing the event listener to the document instead of the videoElement fixes it

**Comment by whitecrownclown** [comment]
Yeah, but I wanted to keep it on the video wrapper, giving it focus seems to do the job.
