### ISSUE TITLE
Volume slider hides early

### ISSUE THREAD

**Issue by legraphista** [whitecrownclown/videoplayer#3]
While dragging the volume slider, if your pointer deviates a bit above or below the slider element, the component collapses while you are still using it

**Comment by whitecrownclown** [comment]
This issue might be the reason why youtube shows the slider all the time.

**Comment by legraphista** [comment]
Can it be fixed by having a toggle preventing it to be hidden while in use?
Or maybe the element can be made as tall as the bottom panel so that it doesn't lose hover

**Comment by whitecrownclown** [comment]
I think it can be fixed by not hiding it when slider is `mousedown`. That's what youtube does, but closes it on outside click (which isn't really applicable here since the video is fullscreen).
